### ISSUE TITLE
Reverse DNS lookups should be disabled

### ISSUE THREAD

**Issue by dbrugman-pega** [pegasystems/docker-pega-web-ready#104]
**Describe the bug**
The Tomcat connector will automatically do reverse DNS lookups for the source IPs of requests. It uses this, for example, to log human readable hostnames instead of IP addresses in the access log files. However, the Tomcat container is typically deployed in a cluster, where external traffic is routed via a load balancer (e.g. AWS ALB), Envoy or kube proxy, etc. So the source IP arriving at Tomcat will not be the original source IP, but instead the IP of the internal routing component (the original source IP is then often found in the 'x-forwarded-for' header). That is: all reverse DNS lookups result in the hostname of the routing component. The DNS lookup adds cost, without providing any value. What's more, the DNS lookups have been identified as a source of spikes in response times - at least in some environments. Disabling reverse DNS lookups resolves this.

**To Reproduce**
Check the Tomcat access logs - they contain the host names of the internal routing components.

**Expected behavior**
Reverse DNS lookups should be prevented. As a result the access logs will show IP addresses instead.

**Screenshots**
N/a

**Desktop (if applicable, please complete the following information):**
N/a

**Server (if applicable, please complete the following information):**
N/a

**Additional context**
Also see the related Issue #240 of the 'pega-helm-charts' repository. For internal reference, see US-400592

**Comment by misterdorito** [comment]
Per https://tomcat.apache.org/tomcat-9.0-doc/config/http.html#Common_Attributes, the enableLookups attribute of the connector defaults to false.
