### ISSUE TITLE
PegaMKTSMS and PegaMKTEmail are Valid NodeTypes for CDH Deployments

### ISSUE THREAD

**Issue by raghavf1** [pegasystems/docker-pega-web-ready#112]
**Describe the bug**
PegaMKTSMS and PegaMKTEmail are Valid NodeTypes for CDH Deployments and there is no configurational way to pass in those NodeTypes
 
**To Reproduce**
Set the -DNode=PegaMKTSMS or PegaMKTEmail , we get an error from the platform its invalid nodetype the valid applicable NodeTypes are [Search, WebUser, BIX, BackgroundProcessing, Custom1, Custom2, Custom3, Custom4, Custom5, DDS, ADM, Batch, RealTime, RTDG, Stream]

**Expected behavior**
For CDH Deployments we should include- PegaMKTSMS and PegaMKTEmail as a valid NodeTypes

**Additional context**
As of today there is no way to pass the ApplicableNodeTypes environment value to tomcat.
Currently in existing cloud cuttyhunk deployment tomcat images have an option to pass the applicable NodeTypes and we need  similar param in tomcat for CDH deployments in this repo to pass applicableNodeTypes

**Comment by Virusmater** [comment]
Hello, any updates on this? CDH installation requires to have PegaMKTSMS and PegaMKTEmail node types.

**Comment by pega-roska** [comment]
You can set applicable node types by adding `-DapplicableNodeTypes=` to the `JAVA_OPTS` environment variable.
