### ISSUE TITLE
support for custom certificates to be injectable to infinity 

### ISSUE THREAD

**Issue by smootherbug** [pegasystems/docker-pega-web-ready#148]
#146 
**Is your feature request related to a problem? Please describe.**
support for custom certificates to be injectable to infinity 

**Describe the solution you'd like**
Mounting the certificates into the /opt/pega/certs folder and then store the certs into the cacerts file in lib/security folder of java

**Additional context**
Currently we have support only for .cer file, we will need to enhance in the future

**Comment by kishorv10** [comment]
Addressed in #146
