### ISSUE TITLE
Support for external Kafka service as Stream node

### ISSUE THREAD

**Issue by Virusmater** [pegasystems/docker-pega-web-ready#158]
Since 8.7.0 having Pega Stream node is a deprecated configuration. Would be neat to have possibility to configure external Kafka service using environmental variables instead of having need to update prconfig/DSS settings manually.
The same way it was done there for Hazelcast and Cassandra

**Comment by AdamaPega** [comment]
@Virusmater the possibility to configure external Kafka in Helm charts is being developed. We expect to make it available by the end of August.

**Comment by menaibluey** [comment]
> @Virusmater the possibility to configure external Kafka in Helm charts is being developed. We expect to make it available by the end of August.

Hi, we're now almost of of September. Has there been any progress with this?

**Comment by AdamaPega** [comment]
@menaibluey please follow these two pull requests:
- https://github.com/pegasystems/pega-helm-charts/pull/450
- https://github.com/pegasystems/docker-pega-web-ready/pull/169

The implementation is completed. We are running integration tests against different clouds before we can release the changes.

**Comment by MadhuriArugula** [comment]
@AdamaPega I see that the PR's are already merged, are we good to close this issue?

**Comment by misterdorito** [comment]
@AdamaPega as the PR's above have been merged, can this issue be closed?

**Comment by AdamaPega** [comment]
@misterdorito , we can close the issue

**Comment by misterdorito** [comment]
Thanks!
