### ISSUE TITLE
build fails on gpg errors

### ISSUE THREAD

**Issue by viper0131** [pegasystems/docker-pega-web-ready#17]
Current build fails with gpg errors

`gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: cannot open '/dev/tty': No such device or address
gpg: cannot open '/dev/tty': No such device or address
gpg: cannot open '/dev/tty': No such device or address
gpg: cannot open '/dev/tty': No such device or address
gpg: /root/.gnupg/trustdb.gpg: trustdb created`

easy-fix is to add --no-tty to gpg paramaters

**Comment by dcasavant** [comment]
This should be fixed in the latest code that supports Pega 8.2+ since the download is no longer required.  Please reopen this issue if you disagree!
