### ISSUE TITLE
Pega8 support

### ISSUE THREAD

**Issue by viper0131** [pegasystems/docker-pega-web-ready#18]
Please add support for native pega8.x version
(remove sma, upgrade tomcat to version 8.5 or higher)

**Comment by cdancy** [comment]
@dcasavant what is the status of this project given other internal initiatives around docker/tomcat/pega?

**Comment by ilyasahmed24** [comment]
when will the update for pega 8.x happen ?

**Comment by dcasavant** [comment]
Pega Infinity support is coming very soon.  The Docker images will first be available via the standard software distribution kit and then reflected on GitHub a short time later.

**Comment by dcasavant** [comment]
Support is being reviewed as part of #19

**Comment by dcasavant** [comment]
Merged
