### ISSUE TITLE
enable the configuration of maxDays attribute for Access Log Valve

### ISSUE THREAD

**Issue by byroncollins** [pegasystems/docker-pega-web-ready#187]
**Is your feature request related to a problem? Please describe.**
The housekeeping/purging of localhost_access_logs cannot be managed using configuration. The logs rotate every day for the life of the container.

**Describe the solution you'd like**
I would like to add the [maxDays ](https://tomcat.apache.org/tomcat-9.0-doc/config/valve.html#Access_Log_Valve/Attributes)attribute whose value can be adjusted using an environment variable.

This would require set_env.sh to add the following [system property](https://tomcat.apache.org/tomcat-9.0-doc/config/systemprops.html) to CATALINA_OPT

```bash
CATALINA_OPTS="$CATALINA_OPTS -Dorg.apache.tomcat.util.digester.PROPERTY_SOURCE=org.apache.tomcat.util.digester.EnvironmentPropertySource
```
I propose that the default value of maxDays be -1, which means never deleting the old files, which matches existing behaviour.

**Describe alternatives you've considered**
We add this value when building our pega containers using the pega-ready container as the base, but the retention period is hardcoded.

```bash
LINE=$(grep -n "prefix=\"localhost_access_log\"" ${CATALINA_HOME}/conf/server.xml | cut -d: -f1) \
 sed -i "${LINE}s/$/ maxDays\=\"90\"/" ${CATALINA_HOME}/conf/server.xml
```

**Additional context**

**Comment by kishorv10** [comment]
#188 We decided to not to purse with the enhancement
