### ISSUE TITLE
Env Variable

### ISSUE THREAD

**Issue by amitdangayach** [pegasystems/docker-pega-web-ready#191]
**Describe the bug**
How to define custom variable in context.xml and how to refer it in pega code

**To Reproduce**
How to define custom variable in context.xml and how to refer it in pega code.

**Expected behavior**
How to define custom variable in context.xml and how to refer it in pega code.

**Screenshots**

**Desktop (if applicable, please complete the following information):**

**Server (if applicable, please complete the following information):**
 - OS: [e.g. Ubuntu 18.04]
 - Environment: [e.g. Open Source Kubernetes 1.11]

**Additional context**

**Comment by arvasrikanth** [comment]
@amitdangayach can you provide more details on your use case, what is the custom variable you are talking about and how you want use in pega code ?

**Comment by kishorv10** [comment]
@amitdangayach Can you respond to above question?

I would like to provide more details about different configuration options available to update `context.ml`.
1. Pega shipped OOTB data source properties can be updated through environment variable, ref [here](https://github.com/pegasystems/docker-pega-web-ready?tab=readme-ov-file#advanced-jdbc-configuration) for the list. These properties overrides the defaults in the context.xml
2. Through pega-helm-charts, extra data source configurations or any other resources can be set using CONEXT_XML_SNIPPET environment variable ref [here](https://github.com/pegasystems/pega-helm-charts/issues/121) for more details.
