### ISSUE TITLE
Deletion of https://hub.docker.com/r/pegasystems/pega7-tomcat-read

### ISSUE THREAD

**Issue by corey-bailey** [pegasystems/docker-pega-web-ready#25]
deletion of a dockerhub repo kills external teams making pulls.

If you're going to make a new dockerhub for a different version, you should at least keep the old version...

This Breaks Customer Builds in Production!

**Comment by dcasavant** [comment]
The pega7-tomcat-ready docker image was pulled down to avoid confusion with the updated pega-ready image.  The older image is not meant for production use and is not supported for that.  The new Docker image is supported for production use.

The pega7-tomcat-ready project has been made temporarily visible again to allow for builds, but it will be pulled down permanently in a few months (date to be posted on the DockerHub page).

**Comment by cdancy** [comment]
@dcasavant I tend to agree with the OP in that deleting projects/repos is generally a bad idea and should never really be done. However ... we are in a bit of pickle in that this will confuse customers/end-users of our images. I've seen other projects create something like "sunset projects" where they are moved out of the "main company project" and into something like a "pegasystems-sunset" project with a giant banner saying "this is deprecated, please don't use, you're on your own if you do, use X instead".

**Comment by dcasavant** [comment]
@cdancy Unfortunately even if we move this, builds will break that depend on the old repo.  The best thing to do here IMO is to deprecate and provide a date to remove.  

Happy to entertain other ideas!

Another alternative is to make the repo private and request access on a user by user basis.  It will still possibly break builds, but we would at least see how actively it is being use and could proactively advocate upgrades to the latest version.

**Comment by viper0131** [comment]
update the latest image on dockhub, add warnings to readme and put a message in the startup log to warn about this being an outdated version and point to the new one.
Never just remove images, I think that's bad behaviour.

**Comment by viper0131** [comment]
I used it as a base image, build ton's of things on top of it to make it production ready.
I'm going to migrate to the new images, but it's not on top of my backlog.

**Comment by dcasavant** [comment]
@viper0131 @corey-bailey Good ideas.  A warning has been added to the readme.  The startup log change would require rebuilding and this isn't connected to a build pipeline at the moment (hence why the last update is 1y+ ago).

Will see what we can do about keeping this around for a reasonable timeframe.

**Comment by dcasavant** [comment]
Reopening to merge with #26

**Comment by dcasavant** [comment]
The pega7-tomcat-ready Docker repository has been removed.  If you have any questions or concerns about the updated images, please feel free to reply or email directly to opensource@pega.com.
