### ISSUE TITLE
Whats the correct way of setting the volumes in the container 

### ISSUE THREAD

**Issue by yokodev** [pegasystems/docker-pega-web-ready#27]
**What directories are important or necessaries for the container to persist data using volumes?**
Currently I have these:
- /usr/local/tomcat/webapps
  - work
  - logs
  - temp
 -/opt/pega/data

Any Suggestion?

**Comment by dcasavant** [comment]
@yokodev What data are you looking to persist?  Is this for web/batch or stream nodes?

I'd also suggest looking at the Helm charts repo here: https://github.com/pegasystems/pega-helm-charts.  That provides a codified example of a Kubernetes deployment - including volume claims as needed.

**Comment by yokodev** [comment]
@dcasavant Well, you got me there...   
How do you know if a tomcat is web/batch or stream?  my guess is that this is web

I have some 7.4 and 8.2 images based on this article [How to run Pega 7.4 in Docker](https://community1.pega.com/community/pega-support/question/how-run-pega-74-docker)   
and came to the configuration above by guessing what my team may need... but was wondering what would be the official way of doing things.   

I will also look at the repo you mention...
Thanks

**Comment by cdancy** [comment]
@yokodev I assume this is a pure docker deployment and not trying to do things through kubernetes?

**Comment by cdancy** [comment]
> or is it something wrong with the docker images

So that depends on which docker image you're referring to. Is that this image from this repo or something you built on your own given the article above?

Generally you can create a volume at the `/opt/pega` directory using whatever means you want to do so. A popular thing to do in the pure docker world is to use a data-container which defines this volume and then wire that up to this container.

**Comment by yokodev** [comment]
Yes, I built it based on the article...  
Regarding the volumes I currently have this mapped to the host   
- /usr/local/tomcat/ 
  - webapps
  - work
  - logs
  - temp
- /opt/pega/data    
I didn't want to lose the logs, and the temp folder is for the search indexes, 
although I have to set the node every time the VM is restarted. Is there a way of setting this permantenly?


![node Name does not persist](https://user-images.githubusercontent.com/17376780/61484284-d27c7280-a95b-11e9-84f3-47ef8d1a6379.png)

**Comment by cdancy** [comment]
@yokodev what is this UI/program you're using to do things? I'm generally familiar with docker command line.

With that said your logic sounds fine enough. As far as setting the node-type permanently you can do that with _this_ image though with the one you built I suspect you'd have to wire things up in your own way to do that. You can use the below query to see how we wire-up setting the NODE_TYPE for this image and perhaps apply that logic however you can to your context.

https://github.com/pegasystems/docker-pega-web-ready/search?q=NODE_TYPE&unscoped_q=NODE_TYPE

**Comment by yokodev** [comment]
@cdancy  That is Pega :)   
So every time I restart the host it gets terribly slow and so, one of the things that help alleviate this is to set the **Host node ID**  on the **Search Index host node setting** (shown above) but it gets wiped out on every restart, so I was wondering if its a volume issue or how do you make it persistent across restarts.

**Comment by cdancy** [comment]
> That is Pega :)

hahaha ... I'm in a different context and assumed you were posting a screenshot of some program to start docker containers. Indeed it is Pega :) So that's just basic docker at this point. I would personally recommend using a data-container as I noted above to make this stupid-simple. Check out the below article to see how to wire things up.

https://boxboat.com/2016/06/18/docker-data-containers-and-named-volumes/

**Comment by yokodev** [comment]
@cdancy  Sorry about that probably I wasn't expressing my ideas in the clearest of ways...   
So my doubt primarily geared towards best practices, and now that someone with knowledge was answering take advantage and throw in, some other issues that I was having...
So, I'm able to persist everything, I just don't know how to persist this setting across reboots( node setting for the search indexes).

**Comment by dcasavant** [comment]
@yokodev What are you using to orchestrate your restarts?  How is the configuration managed?

**Comment by yokodev** [comment]
@dcasavant well its GCP scheduler, and was just trying to figure out a way of persisting this option across reboots. So I thought it may be related to my volume configuration being wrong or something.

**Comment by dcasavant** [comment]
@yokodev I haven't tried the GCP scheduler so I can't advise on that.  I'd suggest moving to GKE (GCP Kubernetes) as that is a supported tool and can be deployed using the Helm charts linked above.

**Comment by yokodev** [comment]
@dcasavant Yes, I know... So because of our requirements within the company sometimes we just need to spawn a single container for a couple of days and not have a full-fledged installation.  
That said, do you guys have plans to provide such docker image so that one is able to just test out something in a single node and then get rid of it?

Any other recommendation is well welcome.


Thanks

**Comment by dcasavant** [comment]
@yokodev With some basic automation of the commands, you can spin up and tear down deployments using GKE as well (and it is the more appropriate tool to solve this problem).  That is how I would suggest running a deployment regardless of the duration.  

Depending on your exact use cases, you can also automate the restoration of a DB from backup or full installation on a run-by-run basis.
