### ISSUE TITLE
Tagged builds not pushing to DockerHub

### ISSUE THREAD

**Issue by dcasavant** [pegasystems/docker-pega-web-ready#31]
Tagged builds should be pushed to DockerHub here: https://cloud.docker.com/u/pegasystems/repository/docker/pegasystems/pega-ready

2.0.0 was pushing successfully.  On the latest version bump to 2.1.0, there is no new tag being pushed.

Expected behavior:
Each build should be pushing _latest_ and _2.1.0_ (as long as that is the current version).  _2.0.0_ is correctly no longer being pushed.

**Comment by cdancy** [comment]
Should we even push `latest` at all? Folks won't really know what they are getting and it's generally bad practice to do so. I would vote for not pushing `latest` at all if it can be helped and force people to use a distinct version so that we are not unnecessarily chasing issues from some version folks think they are on when in fact they are on something else.

And to make matters worse: should they configure things to always pull the latest image of `latest` each time they attempt to refresh their deployment, or bounce some pod, they may get a new version of PRPC they did not expect.

**Comment by dcasavant** [comment]
@cdancy I agree that consumers should be pulling a tagged version (hence the bug).  I do think there are a few good use cases for pulling latest however in development. Maybe that is just the latest tagged version and not latest from master?

In the meantime, this gets the specific tagged version back.

**Comment by viper0131** [comment]
Leave version pinning to the customer. If they wan’t to use latest it should point to the newest version.

**Comment by dcasavant** [comment]
@viper0131 Thanks for the input - I agree there should be a way to keep on the latest version.  The best practice may be published to pin to a particular version to avoid any unexpected changes, but some users would rather have a pipeline to stay up to date.  If we someday end up with separate _BE_ and _Stable_ paths, we may need to reevaluate what _latest_ means, but for now it will stay as-is.

There is also a pull request open for this issue.  Hopefully will get it merged shortly.

**Comment by cdancy** [comment]
I disagree but OK. Leaving it to the customer is just asking for confusion/questions down the road. The term `latest` is akin to using a `+` when using GAV coordinates: you have no idea what you're getting and might get something you don't expect which could break whatever it is you're doing. It's a very convenient thing yes but it comes at a cost which is not immediately clear to end-users until things go wrong and then it's too late.

**Comment by cdancy** [comment]
> pulling latest however in development.

For development use-cases, meaning in house where we are building things, a proper CI flow would be to build the thing we want to use and literally use that as part of the process. The version there should not matter as the code itself will just be using the thing we built. This is more an argument for downstream/customer/end-users who don't understand the implications of using `latest` and think the easy route is "best".

But I've said my peace now! ;)

**Comment by dcasavant** [comment]
Merged.

Images should autobuild every 24h if there are no commits that trigger a build.
