### ISSUE TITLE
Expose CATALINA_OPTS as environment variable

### ISSUE THREAD

**Issue by asasisekar** [pegasystems/docker-pega-web-ready#37]
**Integration with pinpoint APM tools.**
To integrate pinpoint or other APM tools, agent jar path and configurations has to be passed in CATALINA_OPTS. But CATALINA_OPTS is not exposed as environment variable. We are unable to set APM tool configuration in CATALINA_OPTS.

**Describe the solution you'd like**
https://github.com/pegasystems/docker-pega-web-ready/blob/master/tomcat-bin/setenv.sh
CATALINA_OPTS is initialized with empty string. Removing that will help.

**Comment by dcasavant** [comment]
Seems reasonable.  Will get this queued up with the next round of updates.

If you have made the change in a branch, feel free to submit a PR and it may get in sooner :).
