### ISSUE TITLE
Impact of losing  the /kafkadata mount point

### ISSUE THREAD

**Issue by jocatalin** [pegasystems/docker-pega-web-ready#44]
We are transitioning to containerized pega applications (our current platform is [mesos/dcos](https://d2iq.com/solutions/mesosphere) - there's no stateful-set like concept there). What is the actual impact of losing the `/kafkadata` mount point (e.g. during an update, due to a container failure, or if the vm that runs the container goes down) ? Assuming 1 new pega container (re)starts, and it doesn't have the `/kafkadata` folder, will that result in data loss? Same question in case all the pega container instances (of the same application) are missing the `/kafkadata` mount (after an update, or in case of nodes failure)?

**Comment by dcasavant** [comment]
Hi @jocatalin, as you pointed out, this particular scenario would result in data loss.  There are other networking challenges that may be encountered as well as the models for mesos/dcos and Kubernetes are not the same.

At this time Pega only supports Kubernetes for container based deployments.
