### ISSUE TITLE
Open source the git repo / Dockerfile for the base image pegasystems/tomcat:9-jdk11

### ISSUE THREAD

**Issue by jocatalin** [pegasystems/docker-pega-web-ready#45]
**Is your feature request related to a problem? Please describe.**
In order to keep our docker images in sync with pegasystems we would like to use your base image: `pegasystems/tomcat:9-jdk11` and build on top of that. 

**Describe the solution you'd like**
I would like to see the Dockefile / git repository used to build that image. Can you opensource that?

**Comment by dcasavant** [comment]
Hi @jocatalin, we are always evaluating what code we can open source.  This built-on image has come up before but there are currently no plans to take it to GitHub.  I will keep this request in mind and will see what we can do in the future!
