### ISSUE TITLE
Pega images based on Red Hat Universal Base Image (UBI)?

### ISSUE THREAD

**Issue by PegaBasis** [pegasystems/docker-pega-web-ready#52]
Hello Pegasystems,

A requirement from our organisation will be that all container images must be build on a Red Hat Universal Base Image. Could you give me any information what base image the Pega images are build on?

If the Pega images are build on another base image (which I expect), would it be possible to rebuild these images with a Red Hat Universal Base Image? Either by you or by us.

Thank you in advance.

**Comment by dcasavant** [comment]
Transferred this issue to the Pega Docker image project.  See the project readme for information about [image customizations](https://github.com/pegasystems/docker-pega-web-ready#image-customizations).

This image is currently built on top of a managed Ubuntu base image from Google, though that may change in the future.  Any changes to this image stack will be thoroughly tested and verified by Pegasystems.  No changes in the base image are currently planned or scheduled.

**Comment by dcasavant** [comment]
Closing for now.  Please reopen if you wish to revisit or feel free to reach out to me directly to discuss.
