### ISSUE TITLE
Being able to specify different database credentials for different schemes

### ISSUE THREAD

**Issue by Jasperscheper** [pegasystems/docker-pega-web-ready#53]
We have different db users for the RULES and DATA schemes.

How to configure this in the docker container?

**Comment by Jasperscheper** [comment]
Please update us on this issue

**Comment by zitikay** [comment]
Closing as this is not a supported configuration. If you want to move forward anyways, please refer to https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-configuration-files for custom context.xml injection, where you can specify separate DataSources for PegaRULES and PegaDATA with separate users.
