### ISSUE TITLE
prconfig/dsm/services setting doesn't get set for Stream nodes

### ISSUE THREAD

**Issue by pegadave** [pegasystems/docker-pega-web-ready#54]
**Describe the bug**
Currently the intention is for the 'prconfig/dsm/services' prconfig setting to get set via JNDI Environment entry contained within the /usr/local/tomcat/conf/Catalina/localhost/prweb.xml file.  This is not happening (and for that matter seems never to have happened) because the prconfig keys are for lack of a better term not JNDI friendly.

The prweb.xml file for Stream nodes contains the following:
```
  <Environment name="prconfig/dsm/services" value="StreamServer" type="java.lang.String" />
  <Environment name="prconfig/dsm/services/stream/pyUnpackBasePath" value="/tmp/kafka" type="java.lang.String" />
  <Environment name="prconfig/dsm/services/stream/server_properties/unclean.leader.election.enable" value="false" type="java.lang.String" />
```

These environment settings all start with the common root of 'prconfig/dsm/services' and this is problematic.  The name 'prconfig/dsm/services' is bound to a string, however when tomcat is building out the JNDI environment on startup, it processes of the other config settings (like 'prconfig/dsm/services/stream/pyUnpackBasePath') and in doing so builds out the intervening JNDI contexts ('prconfig', 'prconfig/dsm', 'prconfig/dsm/services', ...).  Depending on the order in which this file is processed, it seems that you either see this message during startup:

```
20-Dec-2019 12:01:31.658 SEVERE [main] org.apache.catalina.core.NamingContextListener.addEnvironment naming.invalidEnvEntryValue
```
[catalina_behavior1.log](https://github.com/pegasystems/docker-pega-web-ready/files/4071825/catalina_behavior1.log)

or in other environments you see a ClassCastException while processing the longer prconfig keys because tomcat attempts to cast  the object bound to 'prconfig/dsm/services' to a javax.naming.Context but the name is already bound to a java.lang.String.  Both behaviors have been seen -- it is not clear why there is a behavioral difference, but it is my suspicion that a dependency (os perhaps) being pulled into more recent docker images is responsible.

**To Reproduce**
Use the pega-helm-charts to deploy Pega into K8S environment.  Examine the /usr/local/tomcat/logs/catalina*.log for log messages related to the processing of prweb.xml.

**Expected behavior**
The setting ('prconfig/dsm/services') would be set (with value 'StreamServer') for the Pega application.  Additionally, no error messages would be reported while tomcat builds out the JNDI environment.

**Screenshots**
n/a

**Desktop (if applicable, please complete the following information):**
n/a

**Server (if applicable, please complete the following information):**
n/a

**Additional context**
n/a

**Comment by pegadave** [comment]
[catalina_behavior2.log](https://github.com/pegasystems/docker-pega-web-ready/files/4071836/catalina_behavior2.log)

This is the secondary behavior described.

**Comment by dcasavant** [comment]
Merged
