### ISSUE TITLE
Support for authenticated JDBC driver URIs

### ISSUE THREAD

**Issue by davidlee-pega** [pegasystems/docker-pega-web-ready#61]
**Authenticated JDBC Driver URI**
Currently, we are unable to set JDBC_DRIVER_URI to a web server that requires authentication.  Authenticated JDBC Driver URI support will be very helpful for easily launching Pega web containers within unsecured networks and when driver downloads requires authentication.    

**Describe the solution you'd like**
It would be great if the following variables where exposed so that JDBC_DRIVER_URI can reside on an authenticated server.  
- JDBC_DRIVER_URI_USERNAME
- JDBC_DRIVER_URI_PASSWORD

**Describe alternatives you've considered**
It would be added complexity to construct our own image with the drivers baked-in, hence, the first choice would be support for authenticated JDBC driver URIs.

**Comment by Emilio-Pega** [comment]
Another thing to note is that this capability *used to exist* before the images were fully moved over to github in this repo.  For example in [8.1.0](https://git.pega.io/projects/PRPC/repos/prpc-platform/browse/infrastructure/distribution/docker/images/pega/Dockerfile?at=refs%2Fheads%2Frelease%2F8.1.0#21-23)

I feel like this was a feature that was not appropriately ported over

**Comment by Emilio-Pega** [comment]
This will also **block** adoption of [EPIC-59878 Ability to launch multiple Platform dockerized tomcats](https://agilestudio.pega.com/prweb/AgileStudio/app/agilestudio/epics/EPIC-59878) since many of our at-home developers use bin.pega.io for their downloads which is a secured artifactory

**Comment by cdancy** [comment]
Interesting that this was somehow missed or wasn't moved over. Do we know the decision behind that? Wondering if there is something we may be missing here...

**Comment by Emilio-Pega** [comment]
Actually, looking at various versions, I think by time 8.2 rolled out it was already gone, I don't remember the timings on when pega ready was created, so maybe it was gone before then.

Unfortunately the documentation in the platform repo readme remained stubbornly incorrect

**Comment by cdancy** [comment]
Good times ;)

**Comment by Emilio-Pega** [comment]
@cdancy Can we get an ETA on this enhancement, its actually pretty annoying especially with everyone working from home.  If we want to download the driver from the authenticated bin.pega.io artifactory for speed

**Comment by viper0131** [comment]
Downloading drivers is not a real docker way of doing things. I recommend to create your own layer on top of the base image where you create your owns specific needs. 

Downloading drivers means that functionality can change between runs.

**Comment by Emilio-Pega** [comment]
To me that seems like an odd position to take for this specific image given that it exposes a JDBC_DRIVER_URI env var and documents it as how to provide the driver.

If what you are saying is true the base image should not expose a URI or document it, but isnead just come pre-packaged with a driver -or- simly not work at all until its extended

**Comment by viper0131** [comment]
It's not that odd I think. This is the 'ready' image.

from the readme: "This ready Docker image represents one component of a full image you can use to run a Pega node. It is built on top of Tomcat but does not contain the Pega .war file (hence it is ready for the .war file...."

So its ready for war and jdbc?

**Comment by misterdorito** [comment]
This is fixed by #160
