### ISSUE TITLE
Readme for /kafkadata mount point is incorrect

### ISSUE THREAD

**Issue by Emilio-Pega** [pegasystems/docker-pega-web-ready#62]
**Describe the bug**
The readme indicates that the kafka mount point is `/kafkadata` but I can see clearly in the files that its actually using `/opt/pega/kafkadata`

**To Reproduce**
N/A

**Expected behavior**
Readme should be accurate

**Screenshots**
![Capture](https://user-images.githubusercontent.com/54679517/75453865-8e663d00-5942-11ea-843b-ee4dd6413a36.PNG)

![Capture1](https://user-images.githubusercontent.com/54679517/75454011-c1103580-5942-11ea-8903-f6bb0ca30488.PNG)

![Capture3](https://user-images.githubusercontent.com/54679517/75454023-c7061680-5942-11ea-9d54-36b32065035d.PNG)

**Desktop (if applicable, please complete the following information):**
N/A

**Server (if applicable, please complete the following information):**
N/A

**Additional context**
N/A

**Comment by cdancy** [comment]
@Emilio-Pega just send in the PR! :)

**Comment by Emilio-Pega** [comment]
I will when I have time :)
