### ISSUE TITLE
Not able to access /opt/pega/prweb permission denied.

### ISSUE THREAD

**Issue by shashikant-koder** [pegasystems/docker-pega-web-ready#79]
When i run the fully baked pega image using docker-pega-web-ready getting below errors:-
cp: cannot create directory '/opt/pega/prweb/META-INF': Permission denied
cp: cannot create directory '/opt/pega/prweb/WEB-INF': Permission denied
cp: cannot create regular file '/opt/pega/prweb/archive.info': Permission denied
cp: cannot create directory '/opt/pega/prweb/diagnostic': Permission denied
cp: cannot create directory '/opt/pega/prweb/images': Permission denied
Loading prlog4j2 from /opt/pega/config/prlog4j2.xml...
cp: cannot create regular file '/opt/pega/prweb/WEB-INF/classes/': No such file or directory
Loading prconfig from /opt/pega/config/prconfig.xml...
cp: cannot create regular file '/opt/pega/prweb/WEB-INF/classes/': No such file or directory

Looks like the image does not have proper permission for pegauser to access /opt/pega/prweb

**Comment by zitikay** [comment]
Linked issue instead of mentioning it. This issue should be resolved by PR
