### ISSUE TITLE
Pega image doesn't have the Pega Installer

### ISSUE THREAD

**Issue by cloudteam1** [pegasystems/docker-pega-web-ready#97]
Hi Team,

I've tried to use the same Dockerfile and looks like this image pegasystems/tomcat:9-jdk11 as releasedoesn't have the Pega installer. Because I've tried to execute the same and Tomcat is able to launch but its throwing an error as Message The requested resource [/prweb] is not available

Also, I've tried to check the same under the Tomcat container and not able to see the prweb installer things. Please do let us know if we need to download and use it manually or can configure the things in Docker file itself.

**Comment by dcasavant** [comment]
The tomcat image you reference is a dependency for this project. It is not intended to be used separately. For access to the Pega Installer image, please follow the instructions [in the Helm Chart readme](https://github.com/pegasystems/pega-helm-charts/blob/master/docs/prepping-local-system-runbook-linux.md#deploying-pega-platform-using-pega-provided-docker-images).

**Comment by cloudteam1** [comment]
Hi @dcasavant

Thanks for sharing the article, but I've already followed to deploy the war and after that its fixed. Now, I am facing an issue with the login screen which username and password should I need to use, Please confirm.

As, I've tried to use the default one:- Administrator@pega.com and install as password, but that's not working. Please do let me know if i"ll use this docker image then which password will work.

**Comment by MadhuriArugula** [comment]
@cloudteam1 which version of helm charts were used to perform DB installation? The latest charts versioned 1.3.5 have been verified. 

Admin password needs to be explicitly set by the user [here](https://github.com/pegasystems/pega-helm-charts/blob/master/charts/pega/values.yaml#L230) as documented in [README](https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-database-installation-and-upgrades).

**Comment by cloudteam1** [comment]
HI @MadhuriArugula 

I am following this document basically, I am trying to use my own Docker image and there Pega screen is showing after building up the containers. But If am trying to put the default username & password then its not accepting. 

Could you please check & let me know.

**Comment by MadhuriArugula** [comment]
> HI @MadhuriArugula
> 
> I am following this document basically, I am trying to use my own Docker image and there Pega screen is showing after building up the containers. But If am trying to put the default username & password then its not accepting.
> 
> Could you please check & let me know.

Please refer to [README](https://github.com/pegasystems/pega-helm-charts/tree/master/charts/pega#pega-database-installation-and-upgrades) if you are using [platform/installer](https://github.com/pegasystems/pega-helm-charts/blob/master/docs/prepping-local-system-runbook-linux.md#deploying-pega-platform-using-pega-provided-docker-images) for installation. If you have performed installation through helm charts, refer to installer.adminPassword in values.yaml where you might have configured application password or if you still have Installation namespace in your cluster, look for "ADMIN_PASSWORD" under pega-install-environment-config in ConfigMap object. 

If you haven't performed database installation through helm charts, please check with your administrator.

**Comment by cloudteam1** [comment]
Hi @MadhuriArugula 

I am using this Docker https://github.com/pegasystems/docker-pega-web-ready/blob/master/Dockerfile

Please share where I need to mentioned the Admin password for this file.

**Comment by MadhuriArugula** [comment]
> Hi @MadhuriArugula
> 
> I am using this Docker https://github.com/pegasystems/docker-pega-web-ready/blob/master/Dockerfile
> 
> Please share where I need to mentioned the Admin password for this file.

As we [already ](. https://github.com/pegasystems/docker-pega-web-ready/issues/97#issuecomment-760234286 )mentioned, this is not the right image to update the admin password

How was the database installation performed in your case?

**Comment by MadhuriArugula** [comment]
Closing as the thread is stale and not an actual issue in image.
