### ISSUE TITLE
The default initial JDBC connection count is too high for large clusters

### ISSUE THREAD

**Issue by dbrugman-pega** [pegasystems/docker-pega-web-ready#99]
**Describe the bug**
The default initial JDBC connection count (JDBC_INITIAL_SIZE) is currently 10, which higher than needed, and too high for large clusters. When multiple PRPC instances start at the same time, this can lead to large connection spikes, potentially exhausting the maximum number of connections configured at the database. A value of 4 should be sufficient.

**To Reproduce**
This is non-trivial to reproduce, since it requires a large cluster. But outages due to connection spikes at startup have been observed in large clusters. Those were resolved by lowering this value to 4.

**Expected behavior**
When multiple PRPC instances start concurrently, this should not lead to exhaustion of DB connections.

**Screenshots**
n/a

**Desktop (if applicable, please complete the following information):**
n/a

**Server (if applicable, please complete the following information):**
n/a

**Additional context**
For internal reference, also see US-400591

**Comment by shashikant-koder** [comment]
This change has been done.  https://github.com/pegasystems/docker-pega-web-ready/blob/65a822bf41bbddf5d30465942ca4e3f146c67681/Dockerfile#L85
